label: Ordinamento
description: 'Determina l’ordine di ordinamento degli elementi. I valori più alti vengono mostrati per primi. Questo campo sostituisce l’ordinamento predefinito basato sulla data di pubblicazione.'
